name: CI - MLflow Project Training

on:
  push:
    branches: [main, master]
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: '3.10'

      - name: Install MLflow
        run: |
          pip install mlflow

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . -P n_estimators=200 -P max_depth=10 -P min_samples_split=2